import type {
  MarketQuote,
  MarketFundamentals,
  InvestmentAnalysis,
  RiskCategory,
  SentimentType,
} from '../types/market';
import { analyzeAsset } from '../../server/scoringEngine';
import rawData from '../data/market_data.json';

// Liquid universe benchmark dataset
export const BENCHMARK_ASSETS: {
  quote: MarketQuote;
  fundamentals: MarketFundamentals;
}[] = (() => {
  const defaults: { quote: MarketQuote; fundamentals: MarketFundamentals }[] = [
  {
    quote: {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      price: 438.45,
      change: 3.25,
      changePercent: 0.75,
      fiftyTwoWeekHigh: 468.35,
      fiftyTwoWeekLow: 388.04,
      dayHigh: 441.2,
      dayLow: 435.8,
      marketCap: 3260000000000,
      peRatio: 36.4,
      eps: 12.05,
      dividendYield: 0.0069,
      beta: 0.89,
      volume: 18400000,
      avgVolume: 20100000,
      sector: 'Technology',
      industry: 'Software - Infrastructure',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      revenueGrowth: 0.152,
      profitMargin: 0.358,
      returnOnEquity: 0.388,
      debtToEquity: 0.42,
      freeCashFlow: 74000000000,
      priceToBook: 12.4,
      forwardPE: 31.2,
      trailingPE: 36.4,
      trailingEps: 12.05,
      beta: 0.89,
      fiftyTwoWeekChange: 0.28,
      summary: 'Microsoft Corporation develops and supports software, services, devices, and solutions including Azure cloud, Office 365, and AI integrations.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      price: 138.25,
      change: 4.15,
      changePercent: 3.10,
      fiftyTwoWeekHigh: 140.76,
      fiftyTwoWeekLow: 45.43,
      dayHigh: 139.5,
      dayLow: 134.8,
      marketCap: 3390000000000,
      peRatio: 52.8,
      eps: 2.62,
      dividendYield: 0.0003,
      beta: 1.68,
      volume: 54000000,
      avgVolume: 62000000,
      sector: 'Technology',
      industry: 'Semiconductors',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      revenueGrowth: 1.22,
      profitMargin: 0.55,
      returnOnEquity: 1.15,
      debtToEquity: 0.18,
      freeCashFlow: 52000000000,
      priceToBook: 42.1,
      forwardPE: 41.0,
      trailingPE: 52.8,
      trailingEps: 2.62,
      beta: 1.68,
      fiftyTwoWeekChange: 1.85,
      summary: 'NVIDIA Corporation provides graphics, compute, and networking solutions powering accelerated computing and enterprise generative artificial intelligence.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'VOO',
      name: 'Vanguard S&P 500 ETF',
      price: 535.10,
      change: 2.10,
      changePercent: 0.39,
      fiftyTwoWeekHigh: 541.20,
      fiftyTwoWeekLow: 395.40,
      dayHigh: 536.4,
      dayLow: 533.2,
      marketCap: 1250000000000,
      peRatio: 26.5,
      eps: 20.19,
      dividendYield: 0.0135,
      beta: 1.00,
      volume: 4800000,
      avgVolume: 5200000,
      sector: 'Diversified Large Cap',
      industry: 'Broad Market ETF',
      currency: 'USD',
      type: 'etf',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'VOO',
      name: 'Vanguard S&P 500 ETF',
      revenueGrowth: 0.08,
      profitMargin: 0.18,
      returnOnEquity: 0.22,
      debtToEquity: null,
      freeCashFlow: null,
      priceToBook: 4.8,
      forwardPE: 23.0,
      trailingPE: 26.5,
      trailingEps: 20.19,
      beta: 1.00,
      fiftyTwoWeekChange: 0.24,
      summary: 'Vanguard S&P 500 ETF invests in stocks in the S&P 500 Index, representing 500 of the largest U.S. companies across diverse industries.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      price: 232.85,
      change: 1.45,
      changePercent: 0.63,
      fiftyTwoWeekHigh: 237.23,
      fiftyTwoWeekLow: 164.08,
      dayHigh: 234.1,
      dayLow: 231.2,
      marketCap: 3540000000000,
      peRatio: 34.2,
      eps: 6.81,
      dividendYield: 0.0043,
      beta: 1.08,
      volume: 48200000,
      avgVolume: 51000000,
      sector: 'Technology',
      industry: 'Consumer Electronics',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      revenueGrowth: 0.049,
      profitMargin: 0.24,
      returnOnEquity: 1.52,
      debtToEquity: 1.45,
      freeCashFlow: 104000000000,
      priceToBook: 48.2,
      forwardPE: 28.5,
      trailingPE: 34.2,
      trailingEps: 6.81,
      beta: 1.08,
      fiftyTwoWeekChange: 0.31,
      summary: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'GOOGL',
      name: 'Alphabet Inc.',
      price: 178.60,
      change: -0.90,
      changePercent: -0.50,
      fiftyTwoWeekHigh: 191.75,
      fiftyTwoWeekLow: 129.40,
      dayHigh: 180.3,
      dayLow: 177.5,
      marketCap: 2200000000000,
      peRatio: 23.8,
      eps: 7.50,
      dividendYield: 0.0045,
      beta: 1.05,
      volume: 22000000,
      avgVolume: 24500000,
      sector: 'Communication Services',
      industry: 'Internet Content & Information',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'GOOGL',
      name: 'Alphabet Inc.',
      revenueGrowth: 0.136,
      profitMargin: 0.28,
      returnOnEquity: 0.31,
      debtToEquity: 0.09,
      freeCashFlow: 71000000000,
      priceToBook: 6.8,
      forwardPE: 20.4,
      trailingPE: 23.8,
      trailingEps: 7.50,
      beta: 1.05,
      fiftyTwoWeekChange: 0.32,
      summary: 'Alphabet Inc. provides Google search, YouTube, Android, Google Play, Cloud platforms and innovative enterprise hardware.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'AMZN',
      name: 'Amazon.com, Inc.',
      price: 194.20,
      change: 1.80,
      changePercent: 0.94,
      fiftyTwoWeekHigh: 201.20,
      fiftyTwoWeekLow: 118.35,
      dayHigh: 195.4,
      dayLow: 192.6,
      marketCap: 2020000000000,
      peRatio: 42.6,
      eps: 4.56,
      dividendYield: 0.0,
      beta: 1.14,
      volume: 38000000,
      avgVolume: 42000000,
      sector: 'Consumer Cyclical',
      industry: 'Internet Retail',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'AMZN',
      name: 'Amazon.com, Inc.',
      revenueGrowth: 0.11,
      profitMargin: 0.082,
      returnOnEquity: 0.21,
      debtToEquity: 0.58,
      freeCashFlow: 53000000000,
      priceToBook: 7.9,
      forwardPE: 33.1,
      trailingPE: 42.6,
      trailingEps: 4.56,
      beta: 1.14,
      fiftyTwoWeekChange: 0.44,
      summary: 'Amazon.com, Inc. focuses on retail sale of consumer products, subscriptions, and web cloud services via AWS.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'QQQ',
      name: 'Invesco QQQ Trust',
      price: 498.80,
      change: 3.40,
      changePercent: 0.69,
      fiftyTwoWeekHigh: 503.52,
      fiftyTwoWeekLow: 355.20,
      dayHigh: 500.2,
      dayLow: 495.6,
      marketCap: 285000000000,
      peRatio: 31.8,
      eps: 15.68,
      dividendYield: 0.0058,
      beta: 1.18,
      volume: 32000000,
      avgVolume: 38000000,
      sector: 'Technology & Innovation',
      industry: 'Nasdaq-100 ETF',
      currency: 'USD',
      type: 'etf',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'QQQ',
      name: 'Invesco QQQ Trust',
      revenueGrowth: 0.14,
      profitMargin: 0.25,
      returnOnEquity: 0.32,
      debtToEquity: null,
      freeCashFlow: null,
      priceToBook: 7.2,
      forwardPE: 27.5,
      trailingPE: 31.8,
      trailingEps: 15.68,
      beta: 1.18,
      fiftyTwoWeekChange: 0.32,
      summary: 'Invesco QQQ tracks the Nasdaq-100 Index, featuring 100 of the largest non-financial innovative companies listed on Nasdaq.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'META',
      name: 'Meta Platforms, Inc.',
      price: 592.50,
      change: 8.20,
      changePercent: 1.40,
      fiftyTwoWeekHigh: 602.95,
      fiftyTwoWeekLow: 298.50,
      dayHigh: 596.1,
      dayLow: 585.3,
      marketCap: 1500000000000,
      peRatio: 28.6,
      eps: 20.72,
      dividendYield: 0.0034,
      beta: 1.22,
      volume: 14500000,
      avgVolume: 15800000,
      sector: 'Communication Services',
      industry: 'Internet Content & Information',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'META',
      name: 'Meta Platforms, Inc.',
      revenueGrowth: 0.22,
      profitMargin: 0.36,
      returnOnEquity: 0.34,
      debtToEquity: 0.24,
      freeCashFlow: 49000000000,
      priceToBook: 8.4,
      forwardPE: 24.2,
      trailingPE: 28.6,
      trailingEps: 20.72,
      beta: 1.22,
      fiftyTwoWeekChange: 0.88,
      summary: 'Meta Platforms builds technologies that help people connect, find communities, and grow businesses across Instagram, Facebook, and WhatsApp.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'SPY',
      name: 'SPDR S&P 500 ETF Trust',
      price: 582.40,
      change: 2.25,
      changePercent: 0.39,
      fiftyTwoWeekHigh: 588.60,
      fiftyTwoWeekLow: 430.20,
      dayHigh: 583.8,
      dayLow: 580.4,
      marketCap: 590000000000,
      peRatio: 26.6,
      eps: 21.89,
      dividendYield: 0.0132,
      beta: 1.00,
      volume: 45000000,
      avgVolume: 51000000,
      sector: 'Diversified Large Cap',
      industry: 'Broad Market ETF',
      currency: 'USD',
      type: 'etf',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'SPY',
      name: 'SPDR S&P 500 ETF Trust',
      revenueGrowth: 0.08,
      profitMargin: 0.18,
      returnOnEquity: 0.22,
      debtToEquity: null,
      freeCashFlow: null,
      priceToBook: 4.8,
      forwardPE: 23.1,
      trailingPE: 26.6,
      trailingEps: 21.89,
      beta: 1.00,
      fiftyTwoWeekChange: 0.24,
      summary: 'The SPDR S&P 500 ETF Trust corresponds generally to the price and yield performance of the S&P 500 Index.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'VTI',
      name: 'Vanguard Total Stock Market ETF',
      price: 285.60,
      change: 1.10,
      changePercent: 0.39,
      fiftyTwoWeekHigh: 289.40,
      fiftyTwoWeekLow: 215.10,
      dayHigh: 286.3,
      dayLow: 284.5,
      marketCap: 410000000000,
      peRatio: 25.4,
      eps: 11.24,
      dividendYield: 0.0142,
      beta: 1.01,
      volume: 3100000,
      avgVolume: 3600000,
      sector: 'Total US Market',
      industry: 'Total Market ETF',
      currency: 'USD',
      type: 'etf',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'VTI',
      name: 'Vanguard Total Stock Market ETF',
      revenueGrowth: 0.075,
      profitMargin: 0.17,
      returnOnEquity: 0.20,
      debtToEquity: null,
      freeCashFlow: null,
      priceToBook: 4.4,
      forwardPE: 22.4,
      trailingPE: 25.4,
      trailingEps: 11.24,
      beta: 1.01,
      fiftyTwoWeekChange: 0.23,
      summary: 'Vanguard Total Stock Market ETF tracks the CRSP US Total Market Index, representing 100% of the investable US stock market across all caps.',
      lastUpdated: new Date().toISOString(),
    },
  },
  {
    quote: {
      symbol: 'TSLA',
      name: 'Tesla, Inc.',
      price: 245.20,
      change: -3.80,
      changePercent: -1.53,
      fiftyTwoWeekHigh: 271.00,
      fiftyTwoWeekLow: 138.80,
      dayHigh: 251.0,
      dayLow: 242.4,
      marketCap: 780000000000,
      peRatio: 64.2,
      eps: 3.82,
      dividendYield: 0.0,
      beta: 2.31,
      volume: 68000000,
      avgVolume: 74000000,
      sector: 'Consumer Cyclical',
      industry: 'Auto Manufacturers',
      currency: 'USD',
      type: 'stock',
      lastUpdated: new Date().toISOString(),
    },
    fundamentals: {
      symbol: 'TSLA',
      name: 'Tesla, Inc.',
      revenueGrowth: 0.08,
      profitMargin: 0.12,
      returnOnEquity: 0.19,
      debtToEquity: 0.14,
      freeCashFlow: 4200000000,
      priceToBook: 11.2,
      forwardPE: 55.0,
      trailingPE: 64.2,
      trailingEps: 3.82,
      beta: 2.31,
      fiftyTwoWeekChange: -0.05,
      summary: 'Tesla designs, develops, manufactures, sells, and leases electric vehicles, energy storage systems, and solar panels.',
      lastUpdated: new Date().toISOString(),
    },
  },
  ];

  // Merge live assets pulled by Python script if available
  const liveAssets = (rawData as any)?.assets;
  if (liveAssets && typeof liveAssets === 'object') {
    return defaults.map((item) => {
      const live = liveAssets[item.quote.symbol];
      if (live && live.quote) {
        return {
          quote: { ...item.quote, ...live.quote },
          fundamentals: { ...item.fundamentals, ...(live.fundamentals || {}) },
        };
      }
      return item;
    });
  }

  return defaults;
})();

/**
 * Generate client-side analysis in case of static hosting or network disconnect
 */
export function generateLocalMarketAnalysis(riskProfile: RiskCategory) {
  const analyses: InvestmentAnalysis[] = BENCHMARK_ASSETS.map(({ quote, fundamentals }) => {
    return analyzeAsset(quote, fundamentals, riskProfile);
  });

  analyses.sort((a, b) => b.overallScore - a.overallScore);

  let marketSentiment: SentimentType = 'Positive';
  const indexQuotes = BENCHMARK_ASSETS.filter(a => ['VOO', 'SPY', 'QQQ'].includes(a.quote.symbol));
  const avgChange = indexQuotes.reduce((acc, q) => acc + (q.quote.changePercent || 0), 0) / indexQuotes.length;
  if (avgChange > 0.2) marketSentiment = 'Positive';
  else if (avgChange < -0.4) marketSentiment = 'Cautious';
  else marketSentiment = 'Neutral';

  return {
    riskProfile,
    marketSentiment,
    totalAnalyzed: analyses.length,
    opportunities: analyses,
    lastUpdated: new Date().toISOString(),
  };
}
